### PR TITLE
[#444] Ensure that sensitive information can't be logged intentionall…

### LINKED ISSUE #444: Ensure that sensitive information can't be logged intentionally or by accident
see `Undescribable` protocol on SDK 0.17.0-alpha

We need to ensure that types holding users' keys and addresses can't be picked up by crash reporters or event trackers and put into logs.

This should be made as inobstrusive and simply as possible. It must cover Mirroring APIs and plain description ( e.g: `String(describing:)`).

### PR DESCRIPTION
**Pull request by LukasKorba**
Closes #444

- SensitiveData file holding utilities to hide all strings and data that holds information we don't want to leak or log
- wallet storage fields redacted
- import wallet fields redacted
- create wallet chips redacted
- import wallet reducer changed: BindableStates replaced by bindings to bridge redacted data
- redacted wallet balance
- redacted birthday value (BlockHeight helper)
- Redacted protocol conforming to Undescribable for release/production and testflight builds
- new target for the unredacted debug development
- unit tests fixed
- sensitive data helpers commented
- unit test for conformation to the Undescribable
- memo is redacted

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Does the code abide by the [Coding Guidelines](../blob/main/docs/CODING_GUIDELINES.md)?
- [x] Automated tests: Did you add appropriate automated tests for any code changes?
- [x] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [x] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [x] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/main/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage before and after your changes and when possible, leave it in a better place. [Learn More...](../blob/main/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/main/README.md), [LICENSE.md](../blob/main/LICENSE.md), and [Architecture.md](../blob/main/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

### CODE REVIEW

File: secant/Models/SensitiveData.swift [hunk 1]
```diff
@@ -0,0 +1,110 @@
...
+
+/// Utility that converts a block height to a redacted counterpart.
+extension BlockHeight {
+    var redacted: RedactedBlockHeight { RedactedBlockHeight(data: self) }
+}
+
+// MARK: - Redacted WalletBalance
+
+/// Redacted holder for a wallet balance.
+struct RedactedWalletBalance: Equatable, Redacted {
```
Comment (pacu) [inline secant/Models/SensitiveData.swift:85]: I find this naming a bit rough to code readability.

I wonder if it would be better for us to wrap WalletBalance to a `Balance` type that is bound to the wallet's domain and then apply all this logic. then when you see the type itself you will notice that it conforms to Redacted and that's a redactable balance.

Comment (pacu) [reply secant/Models/SensitiveData.swift:85]: Then you would have 
````Swift
struct Balance: Equatable, Redacted {
   // members of this type
}

extension Balance {
    init(from zcashBalance: WalletBalance)  {
       // initialization of struct's members
    }
}
````

File: secant/UI Components/Chips/WordChipGrid.swift [hunk 2]
```diff
@@ -36,7 +36,7 @@ struct WordChipGrid: View {
 
     init(words: [String], startingAt index: Int, coloredChipColor: Color = .clear) {
```
Comment (pacu) [inline secant/UI Components/Chips/WordChipGrid.swift:37]: We probably want to apply the same as with Phrase. where we use a `Word` model that can conform to  `Redacted`

I'm mostly thinking of a Handled exception or something of that kind from a crash reporting or event tracking library added to this app or to a fork of it being able to record the seed phrase

Comment (pacu) [reply secant/UI Components/Chips/WordChipGrid.swift:37]: It's not far fetch'd. It has happened to wallets of other cryptocurrencies

File: secant/Models/SensitiveData.swift [hunk 3]
```diff
@@ -0,0 +1,110 @@
...
+    /// Use it wisely and never log outcome of this method or share with anybody.
+    func value() -> BlockHeight? {
+        birthday
+    }
+}
+
+// MARK: - Redacted String
+
+/// Redacted holder for a string.
+struct RedactedString: Equatable, Hashable, Redacted {
```
Comment (pacu) [inline secant/Models/SensitiveData.swift:61]: I think this name best describes this type
```suggestion
struct RedactableString: Equatable, Hashable, Redacted {
```

File: secant/Models/SensitiveData.swift [hunk 4]
```diff
@@ -0,0 +1,110 @@
...
+
+// MARK: - Redacted Protocol
+
+/// `Undescribable` comes from the SDK and it is a reliable and tested protocol ensuring custom
+/// destriptions and dumps never print outs the exact value but `--redacted--` instead.
+/// `Redacted` protocol is just a helper so we can let developers to see the sensitive data when
+/// developing and debugging but production or release builds (even testflight) are set to redacted by default.
+/// A special build scheme `<...>-unredacted` is set to hold `UNREDACTED` flags.
+#if UNREDACTED
+protocol Redacted { }
```
Comment (pacu) [inline secant/Models/SensitiveData.swift:19]:
```suggestion
protocol Redactable { }
```

File: secant/Models/SensitiveData.swift [hunk 5]
```diff
@@ -0,0 +1,110 @@
...
+#else
+protocol Redacted: Undescribable { }
```
Comment (pacu) [inline secant/Models/SensitiveData.swift:21]:
```suggestion
protocol Redactable: Undescribable { }
```

**Review by pacu — CHANGES_REQUESTED** [review]
Great work!

I left some comments that could lead to better ergonomics for these changes

File: secant/UI Components/Chips/WordChipGrid.swift (hunk 2 above)
Comment (LukasKorba) [reply secant/UI Components/Chips/WordChipGrid.swift]: updated so words and words: [String] arrays work with RedactableString instead

**Review by Chlup — APPROVED** [review]

File: secant/Features/WalletEventsFlow/Views/TransactionDetailView.swift [hunk 6]
```diff
@@ -96,7 +96,7 @@ extension TransactionDetailView {
 
     func address(mark: RowMark = .neutral, viewStore: WalletEventsFlowViewStore) -> some View {
         Button {
-            viewStore.send(.copyToPastboard(transaction.address))
+            viewStore.send(.copyToPastboard(transaction.address.redacted))
```
Comment (pacu) [inline secant/Features/WalletEventsFlow/Views/TransactionDetailView.swift:99]: Wouldn't this make the clipboard to have a redacted version of the address?

File: secant/Features/WalletEventsFlow/Views/TransactionDetailView.swift [hunk 7]
```diff
@@ -111,7 +111,7 @@ extension TransactionDetailView {
         mark: RowMark = .neutral
     ) -> some View {
         Button {
-            viewStore.send(.copyToPastboard(memo))
+            viewStore.send(.copyToPastboard(memo.redacted))
```
Comment (pacu) [inline secant/Features/WalletEventsFlow/Views/TransactionDetailView.swift:114]: same as above

File: secant/Features/WalletEventsFlow/Views/TransactionDetailView.swift [hunk 8]
```diff
@@ -124,7 +124,7 @@ extension TransactionDetailView {
                     Text("reply-to address included")
                     Spacer()
                     Button {
-                        viewStore.send(.replyTo(transaction.address))
+                        viewStore.send(.replyTo(transaction.address.redacted))
```
Comment (pacu) [inline secant/Features/WalletEventsFlow/Views/TransactionDetailView.swift:127]: same as above

**Review by pacu — CHANGES_REQUESTED** [review]
I think I spotted a bug on the TransactionDetailView. Could you please double check it?

File: secant/Features/WalletEventsFlow/Views/TransactionDetailView.swift (hunk 6 above)
Comment (LukasKorba) [reply secant/Features/WalletEventsFlow/Views/TransactionDetailView.swift:99]: Short answer: no

Long one: it only creates a redacted struct of the string so any attempt to dump it will be redacted. The value inside is still just a String, all unit tests passing. We don't use description of customDump to pass values around, it's only a protection from the logs.

File: secant/Features/WalletEventsFlow/Views/TransactionDetailView.swift (hunk 7 above)
Comment (LukasKorba) [reply secant/Features/WalletEventsFlow/Views/TransactionDetailView.swift:114]: Short answer: no

Long one: it only creates a redacted struct of the string so any attempt to dump it will be redacted. The value inside is still just a String, all unit tests passing. We don't use description of customDump to pass values around, it's only a protection from the logs.

File: secant/Features/WalletEventsFlow/Views/TransactionDetailView.swift (hunk 8 above)
Comment (LukasKorba) [reply secant/Features/WalletEventsFlow/Views/TransactionDetailView.swift:127]: Short answer: no

Long one: it only creates a redacted struct of the string so any attempt to dump it will be redacted. The value inside is still just a String, all unit tests passing. We don't use description of customDump to pass values around, it's only a protection from the logs.

**Review by pacu — APPROVED** [review]
